# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Validate A2UI specification examples

on:
  push:
    branches: [main]
    paths:
      - "specification/**/json/**"
      - ".github/workflows/validate_specifications.yml"
      - "specification/scripts/validate.py"
  pull_request:
    paths:
      - "specification/**/json/**"
      - ".github/workflows/validate_specifications.yml"
      - "specification/scripts/validate.py"

jobs:
  validate:
    name: Validate Specifications
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Enable Corepack
        run: corepack enable

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "22"
          cache: "yarn"

      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run validation script
        run: python3 specification/scripts/validate.py
